### ISSUE TITLE
Not disabling yubiswitch

### ISSUE THREAD

**Issue by calebyoon** [pallotron/yubiswitch#92] opened 2019-12-09 18:47 UTC
Yubiswitch was working properly until a few days ago. (I think it stopped working after i updated to catalina).

Configurations
Yubiswitch 0.12
ProductID: 0x0407
VendorID: 0x1050

**Comment by antonqiu** [comment] 2019-12-13 22:43
Same here.

macOS Catalina
Yubiswitch 0.12
ProductID: 0x0407
VendorID: 0x1050

**Comment by ctrl-tom** [comment] 2019-12-18 12:46
Duplicate of https://github.com/pallotron/yubiswitch/issues/86

**Comment by pallotron** [comment] 2022-09-29 07:56
try the new 0.14 release
i have your same key (0x0407) and it works

**Closed** 2022-09-29 07:56 UTC
