### ISSUE TITLE
Support dropped on MacBook Pro (2020)?

### ISSUE THREAD

**Issue by gjmveloso** [pallotron/yubiswitch#135] opened 2024-10-29 19:16 UTC
I had updated to 0.17 via Homebrew early today and learned that it dropped support for my old Mac. Is that correct?

```
$ uname -a

Darwin 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:27 PDT 2024; root:xnu-11215.41.3~2/RELEASE_X86_64 x86_64
```

Spec:
```
13-inch, 2020, Four Thunderbolt 3 ports
2 GHz Quad-Core Intel Core i5
Intel Iris Plus Graphics 1536 MB
16 GB 3733 MHz LPDDR4X
```

Thanks!

**Comment by davidrothera** [comment] 2024-10-29 19:26
Unfortunately Xcode dropped support for versions older than 10.13 and so to be able to support new builds it was required to update the minimum version.

**Comment by rbergman18** [comment] 2024-10-30 21:00
Can we get a link for 0.16 that is still runnable on the 2020 MBP?

**Comment by rbergman18** [comment] 2024-10-30 21:13
I'm not entirely understanding... MBP 2020 runs Sequoia. Presumably the problem is that Yubiswitch needs to be built as a Universal Binary?

**Comment by davidrothera** [comment] 2024-10-30 21:17
Hmm this does seem strange, as the release process doesn't leverage "Archive" builds it looks like it only included the release build for my architecture.

This must have been a change in a recent Xcode version as no build settings have been changed.

I'll look to re-release v0.17 shortly.

**Comment by davidrothera** [comment] 2024-10-30 22:08
@rbergman18 there is a new release DMG of 0.17 uploaded now which is a universal binary and also now notarised.

**Comment by davidrothera** [comment] 2024-10-30 22:09
@gjmveloso please download the latest version again and retry.

**Comment by gjmveloso** [comment] 2024-11-02 12:58
Hi @davidrothera, just tested manually downloading the most recent .dmg file and I confirm it's now working fine.


Testing with Homebrew didn't went through due to file hash mismatch:
```
Error: SHA256 mismatch
Expected: 48787eadef7df2383a508587ff93932f35800c146c808269def5db99f6dc869c
Actual: da18d8059e42dfe71abaa7211d7da80f4b5f7f0c1c18bad104bd11a0885b633f
```

**Comment by rbergman18** [comment] 2024-11-02 13:19
Can confirm the same experience. homebrew will require only an issue to be
opened to reset the hash.

**Comment by davidrothera** [comment] 2024-11-02 21:39
I've created https://github.com/Homebrew/homebrew-cask/pull/190760 to address the SHA256 mismatch with homebrew

**Comment by davidrothera** [comment] 2024-11-03 09:12
Homebrew issue resolved. Closing.

**Closed by davidrothera** 2024-11-03 09:12 UTC
